#
# Ability to override the name
# overrideName: 
# overrideFullName: 

# Values belonging to address-validation application
app:
  # Name of the application
  name: address-validation
  imageTag: "latest"
  image: "address-validation"
  imageRegistry: "host.docker.internal:5000"
  imagePullPolicy: "Always"
  replicas: 1

  service:
    # For minikube, set this to NodePort, elsewhere use LoadBalancer
    # Use ClusterIP if your setup includes ingress controller
    serviceType: NodePort
    internalPort: 4003
    targetPort: 4003
