apiVersion: v1
name: billing
version: "1.0.0-SNAPSHOT"
appVersion: "1.0.0-SNAPSHOT"
description: Onlineshop implementation for consumer-driven contracts
keywords:
- onlineshop
- workshop
- consumer-driven contracts
- billing
maintainers:
- name: dag.ennenga
  email: dag.ennenga@openknowledge.de
engine: gotpl
